# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
# ---------------------------------------------------------------------------
  # OrgX:
  # ---------------------------------------------------------------------------
  - Name: Izertis
    Domain: izertis.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1