# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.izertis.com:

networks:
  docker-local:

services:

  peer0.izertis.com:
    container_name: peer0.izertis.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.izertis.com
      - CORE_PEER_ADDRESS=peer0.izertis.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.izertis.com:7051
      - CORE_PEER_LOCALMSPID=IZERTISMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/izertis.com/peers/peer0.izertis.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/izertis.com/peers/peer0.izertis.com/tls:/etc/hyperledger/fabric/tls
        - peer0.izertis.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053
    networks:
      - docker-local


  IZERTIScli:
    container_name: IZERTIScli
    image: hyperledger/fabric-tools:1.4.3
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=IZERTIScli
      - CORE_PEER_ADDRESS=peer0.izertis.com:7051
      - CORE_PEER_LOCALMSPID=IZERTISMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/izertis.com/peers/peer0.izertis.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/izertis.com/peers/peer0.izertis.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/izertis.com/peers/peer0.izertis.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/izertis.com/users/Admin@izertis.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    depends_on:
      - peer0.izertis.com
    networks:
      - docker-local
